{
gROOT->LoadMacro("AllHistosBrowser.C");
gROOT->LoadMacro("DrawLine.C");
gROOT->LoadMacro("ErrorPropagation.C");
gROOT->LoadMacro("FitFuncs.C");
gROOT->LoadMacro("FitTools.C");
gROOT->LoadMacro("HistoAutoRange.C");
gROOT->LoadMacro("ManipulateBins.C");
gROOT->LoadMacro("Optimize2D.C");
gROOT->LoadMacro("Ordinals.C");
gROOT->LoadMacro("OutputToFile.C");
gROOT->LoadMacro("PlotASCII.C");
gROOT->LoadMacro("SameHistoPlotter.C");
gROOT->LoadMacro("TwoVarSample.C");
}
